name: "Cloudflare Purge Cache"
description: "Purge a zone's cache via the Cloudflare API"
author: jakejarvis
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/cloudflare.py
      shell: bash
branding:
  color: orange
  icon: trash-2
