name: "Cloudflare Purge Cache"
description: "Purge a zone's cache via the Cloudflare API"
author: jakejarvis
runs:
  using: "composite"
  steps:
    - run: python -m pip install requests
      shell: bash
    - shell: bash
      run: |
      INPUT_CF_API_KEY=${{ inputs.cf_api_key}} \
      INPUT_CF_EMAIL_ADDR=${{ inputs.cf_email_addr}} \
      INPUT_CF_ZONE_NAME=${{ inputs.cf_zone_name }} \
      INPUT_CF_TOKEN=${${{ inputs.cf_token }}:-None} \
      INPUT_CF_PURGE_URLS=${${{ inputs.cf_purge_urls }}:-None} \
      python ${{ github.action_path }}/cloudflare.py
branding:
  color: orange
  icon: trash-2
inputs:
  cf_api_key:
    description: CloudFlare global API key
    required: true
  cf_email_addr:
    description: CloudFlare mail address
    required: true
  cf_token:
    description: CloudFlare new format API token
    required: true
  cf_zone_id:
    description: CloudFlare zone ID
    required: false
  cf_zone_name:
    description: CloudFlare zone name
    required: false
  cf_purge_urls:
    description: List of URLs to purge
    required: false